import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-black py-24 text-center text-white">
        <h1 className="text-2xl font-semibold">Hello World</h1>
      </main>
    </>
  );
}
